//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidade
    {
        public Unidade()
        {
            this.ClienteList = new HashSet<Cliente>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Cliente> ClienteList { get; set; }
    }
}
